import { Injectable } from '@angular/core';
import { Provincia } from '../models/provincia.model';
import { Canton } from '../models/cantones.model';
import { Parroquia } from '../models/parroquias.model';
import { Barrio } from '../models/barrio.model';

@Injectable({
  providedIn: 'root',
})
export class ProvinciaService {
  private provincias: Provincia[] = [
    { id: 1, nombre: 'Azuay' },
    { id: 2, nombre: 'Bolívar' },
    { id: 3, nombre: 'Cañar' },
    { id: 4, nombre: 'Carchi' },
    { id: 5, nombre: 'Cotopaxi' },
    { id: 6, nombre: 'Chimborazo' },
    { id: 7, nombre: 'El Oro' },
    { id: 8, nombre: 'Esmeraldas' },
    { id: 9, nombre: 'Guayas' },
    { id: 10, nombre: 'Imbabura' },
    { id: 11, nombre: 'Loja' },
    { id: 12, nombre: 'Los Rios' },
    { id: 13, nombre: 'Manabi' },
    { id: 14, nombre: 'Morona Santiago' },
    { id: 15, nombre: 'Napo' },
    { id: 16, nombre: 'Pastaza' },
    { id: 17, nombre: 'Pichincha' },
    { id: 18, nombre: 'Tungurahua' },
    { id: 19, nombre: 'Zamora Chinchipe' },
    { id: 20, nombre: 'Galápagos' },
    { id: 21, nombre: 'Sucumbíos' },
    { id: 22, nombre: 'Orellana' },
    { id: 23, nombre: 'Santo Domingo de Los Tsáchilas' },
    { id: 24, nombre: 'Santa Elena' },
    { id: 25, nombre: 'Zonas No Delimitadas' },
  ];

  private cantones: Canton[] = [
    { id: 1, nombre: 'Cuenca', provinciaId: 1 },
    { id: 2, nombre: 'Girón', provinciaId: 1 },
    { id: 3, nombre: 'Gualaceo', provinciaId: 1 },
    { id: 4, nombre: 'Nabón', provinciaId: 1 },
    { id: 5, nombre: 'Paute', provinciaId: 1 },
    { id: 6, nombre: 'Pucara', provinciaId: 1 },
    { id: 7, nombre: 'San Fernando', provinciaId: 1 },
    { id: 8, nombre: 'Santa Isabel', provinciaId: 1 },
    { id: 9, nombre: 'Sigsig', provinciaId: 1 },
    { id: 10, nombre: 'Oña', provinciaId: 1 },
    { id: 11, nombre: 'Chordeleg', provinciaId: 1 },
    { id: 12, nombre: 'El Pan', provinciaId: 1 },
    { id: 13, nombre: 'Sevilla de Oro', provinciaId: 1 },
    { id: 14, nombre: 'Guachapala', provinciaId: 1 },
    { id: 15, nombre: 'Camilo Ponce Enríquez', provinciaId: 1 },
    { id: 16, nombre: 'Guaranda', provinciaId: 2 },
    { id: 17, nombre: 'Chillanes', provinciaId: 2 },
    { id: 18, nombre: 'Chimbo', provinciaId: 2 },
    { id: 19, nombre: 'Echeandía', provinciaId: 2 },
    { id: 20, nombre: 'San Miguel', provinciaId: 2 },
    { id: 21, nombre: 'Caluma', provinciaId: 2 },
    { id: 22, nombre: 'Las Naves', provinciaId: 2 },
    { id: 23, nombre: 'Azogues', provinciaId: 3 },
    { id: 24, nombre: 'Biblián', provinciaId: 3 },
    { id: 25, nombre: 'Cañar', provinciaId: 3 },
    { id: 26, nombre: 'La Troncal', provinciaId: 3 },
    { id: 27, nombre: 'El Tambo', provinciaId: 3 },
    { id: 28, nombre: 'Déleg', provinciaId: 3 },
    { id: 29, nombre: 'Suscal', provinciaId: 3 },
    { id: 30, nombre: 'Tulcán', provinciaId: 4 },
    { id: 31, nombre: 'Bolívar', provinciaId: 4 },
    { id: 32, nombre: 'Espejo', provinciaId: 4 },
    { id: 33, nombre: 'Mira', provinciaId: 4 },
    { id: 34, nombre: 'Montúfar', provinciaId: 4 },
    { id: 35, nombre: 'San Pedro de Huaca', provinciaId: 4 },
    { id: 36, nombre: 'Latacunga', provinciaId: 5 },
    { id: 37, nombre: 'La Maná', provinciaId: 5 },
    { id: 38, nombre: 'Pangua', provinciaId: 5 },
    { id: 39, nombre: 'Pujilí', provinciaId: 5 },
    { id: 40, nombre: 'Salcedo', provinciaId: 5 },
    { id: 41, nombre: 'Saquisilí', provinciaId: 5 },
    { id: 42, nombre: 'Sigchos', provinciaId: 5 },
    { id: 43, nombre: 'Riobamba', provinciaId: 6 },
    { id: 44, nombre: 'Alausi', provinciaId: 6 },
    { id: 45, nombre: 'Colta', provinciaId: 6 },
    { id: 46, nombre: 'Chambo', provinciaId: 6 },
    { id: 47, nombre: 'Chunchi', provinciaId: 6 },
    { id: 48, nombre: 'Guamote', provinciaId: 6 },
    { id: 49, nombre: 'Guano', provinciaId: 6 },
    { id: 50, nombre: 'Pallatanga', provinciaId: 6 },
    { id: 51, nombre: 'Penipe', provinciaId: 6 },
    { id: 52, nombre: 'Cumandá', provinciaId: 6 },
    { id: 53, nombre: 'Machala', provinciaId: 7 },
    { id: 54, nombre: 'Arenillas', provinciaId: 7 },
    { id: 55, nombre: 'Atahualpa', provinciaId: 7 },
    { id: 56, nombre: 'Balsas', provinciaId: 7 },
    { id: 57, nombre: 'Chilla', provinciaId: 7 },
    { id: 58, nombre: 'El Guabo', provinciaId: 7 },
    { id: 59, nombre: 'Huaquillas', provinciaId: 7 },
    { id: 60, nombre: 'Marcabelí', provinciaId: 7 },
    { id: 61, nombre: 'Pasaje', provinciaId: 7 },
    { id: 62, nombre: 'Piñas', provinciaId: 7 },
    { id: 63, nombre: 'Portovelo', provinciaId: 7 },
    { id: 64, nombre: 'Santa Rosa', provinciaId: 7 },
    { id: 65, nombre: 'Zaruma', provinciaId: 7 },
    { id: 66, nombre: 'Las Lajas', provinciaId: 7 },
    { id: 67, nombre: 'Esmeraldas', provinciaId: 8 },
    { id: 68, nombre: 'Eloy Alfaro', provinciaId: 8 },
    { id: 69, nombre: 'Muisne', provinciaId: 8 },
    { id: 70, nombre: 'Quinindé', provinciaId: 8 },
    { id: 71, nombre: 'San Lorenzo', provinciaId: 8 },
    { id: 72, nombre: 'Atacames', provinciaId: 8 },
    { id: 73, nombre: 'Rioverde', provinciaId: 8 },
    { id: 74, nombre: 'La Concordia', provinciaId: 8 },
    { id: 75, nombre: 'Guayaquil', provinciaId: 9 },
    { id: 76, nombre: 'Alfredo Baquerizo Moreno (Juján)', provinciaId: 9 },
    { id: 77, nombre: 'Balao', provinciaId: 9 },
    { id: 78, nombre: 'Balzar', provinciaId: 9 },
    { id: 79, nombre: 'Colimes', provinciaId: 9 },
    { id: 80, nombre: 'Daule', provinciaId: 9 },
    { id: 81, nombre: 'Durán', provinciaId: 9 },
    { id: 82, nombre: 'El Empalme', provinciaId: 9 },
    { id: 83, nombre: 'El Triunfo', provinciaId: 9 },
    { id: 84, nombre: 'Milagro', provinciaId: 9 },
    { id: 85, nombre: 'Naranjal', provinciaId: 9 },
    { id: 86, nombre: 'Naranjito', provinciaId: 9 },
    { id: 87, nombre: 'Palestina', provinciaId: 9 },
    { id: 88, nombre: 'Pedro Carbo', provinciaId: 9 },
    { id: 89, nombre: 'Samborondón', provinciaId: 9 },
    { id: 90, nombre: 'Santa Lucía', provinciaId: 9 },
    { id: 91, nombre: 'Salitre (Urbina Jado)', provinciaId: 9 },
    { id: 92, nombre: 'San Jacinto de Yaguachi', provinciaId: 9 },
    { id: 93, nombre: 'Playas', provinciaId: 9 },
    { id: 94, nombre: 'Simón Bolívar', provinciaId: 9 },
    { id: 95, nombre: 'Coronel Marcelino Maridueña', provinciaId: 9 },
    { id: 96, nombre: 'Lomas de Sargentillo', provinciaId: 9 },
    { id: 97, nombre: 'Nobol', provinciaId: 9 },
    { id: 98, nombre: 'General Antonio Elizalde', provinciaId: 9 },
    { id: 99, nombre: 'Isidro Ayora', provinciaId: 9 },
    { id: 100, nombre: 'Ibarra', provinciaId: 10 },
    { id: 101, nombre: 'Antonio Ante', provinciaId: 10 },
    { id: 102, nombre: 'Cotacachi', provinciaId: 10 },
    { id: 103, nombre: 'Otavalo', provinciaId: 10 },
    { id: 104, nombre: 'Pimampiro', provinciaId: 10 },
    { id: 105, nombre: 'San Miguel de Urcuquí', provinciaId: 10 },
    { id: 106, nombre: 'Loja', provinciaId: 11 },
    { id: 107, nombre: 'Calvas', provinciaId: 11 },
    { id: 108, nombre: 'Catamayo', provinciaId: 11 },
    { id: 109, nombre: 'Celica', provinciaId: 11 },
    { id: 110, nombre: 'Chaguarpamba', provinciaId: 11 },
    { id: 111, nombre: 'Espíndola', provinciaId: 11 },
    { id: 112, nombre: 'Gonzanamá', provinciaId: 11 },
    { id: 113, nombre: 'Macará', provinciaId: 11 },
    { id: 114, nombre: 'Paltas', provinciaId: 11 },
    { id: 115, nombre: 'Puyango', provinciaId: 11 },
    { id: 116, nombre: 'Saraguro', provinciaId: 11 },
    { id: 117, nombre: 'Sozoranga', provinciaId: 11 },
    { id: 118, nombre: 'Zapotillo', provinciaId: 11 },
    { id: 119, nombre: 'Pindal', provinciaId: 11 },
    { id: 120, nombre: 'Quilanga', provinciaId: 11 },
    { id: 121, nombre: 'Olmedo', provinciaId: 11 },
    { id: 122, nombre: 'Babahoyo', provinciaId: 12 },
    { id: 123, nombre: 'Baba', provinciaId: 12 },
    { id: 124, nombre: 'Montalvo', provinciaId: 12 },
    { id: 125, nombre: 'Puebloviejo', provinciaId: 12 },
    { id: 126, nombre: 'Quevedo', provinciaId: 12 },
    { id: 127, nombre: 'Urdaneta', provinciaId: 12 },
    { id: 128, nombre: 'Ventanas', provinciaId: 12 },
    { id: 129, nombre: 'Vínces', provinciaId: 12 },
    { id: 130, nombre: 'Palenque', provinciaId: 12 },
    { id: 131, nombre: 'Buena Fé', provinciaId: 12 },
    { id: 132, nombre: 'Valencia', provinciaId: 12 },
    { id: 133, nombre: 'Mocache', provinciaId: 12 },
    { id: 134, nombre: 'Quinsaloma', provinciaId: 12 },
    { id: 135, nombre: 'Portoviejo', provinciaId: 13 },
    { id: 136, nombre: 'Bolívar', provinciaId: 13 },
    { id: 137, nombre: 'Chone', provinciaId: 13 },
    { id: 138, nombre: 'El Carmen', provinciaId: 13 },
    { id: 139, nombre: 'Flavio Alfaro', provinciaId: 13 },
    { id: 140, nombre: 'Jipijapa', provinciaId: 13 },
    { id: 141, nombre: 'Junín', provinciaId: 13 },
    { id: 142, nombre: 'Manta', provinciaId: 13 },
    { id: 143, nombre: 'Montecristi', provinciaId: 13 },
    { id: 144, nombre: 'Paján', provinciaId: 13 },
    { id: 145, nombre: 'Pichincha', provinciaId: 13 },
    { id: 146, nombre: 'Rocafuerte', provinciaId: 13 },
    { id: 147, nombre: 'Santa Ana', provinciaId: 13 },
    { id: 148, nombre: 'Sucre', provinciaId: 13 },
    { id: 149, nombre: 'Tosagua', provinciaId: 13 },
    { id: 150, nombre: '24 de Mayo', provinciaId: 13 },
    { id: 151, nombre: 'Pedernales', provinciaId: 13 },
    { id: 152, nombre: 'Olmedo', provinciaId: 13 },
    { id: 153, nombre: 'Puerto López', provinciaId: 13 },
    { id: 154, nombre: 'Jama', provinciaId: 13 },
    { id: 155, nombre: 'Jaramijó', provinciaId: 13 },
    { id: 156, nombre: 'San Vicente', provinciaId: 13 },
    { id: 157, nombre: 'Morona', provinciaId: 14 },
    { id: 158, nombre: 'Gualaquiza', provinciaId: 14 },
    { id: 159, nombre: 'Limón Indanza', provinciaId: 14 },
    { id: 160, nombre: 'Palora', provinciaId: 14 },
    { id: 161, nombre: 'Santiago', provinciaId: 14 },
    { id: 162, nombre: 'Sucúa', provinciaId: 14 },
    { id: 163, nombre: 'Huamboya', provinciaId: 14 },
    { id: 164, nombre: 'San Juan Bosco', provinciaId: 14 },
    { id: 165, nombre: 'Taisha', provinciaId: 14 },
    { id: 166, nombre: 'Logroño', provinciaId: 14 },
    { id: 167, nombre: 'Pablo Sexto', provinciaId: 14 },
    { id: 168, nombre: 'Tiwintza', provinciaId: 14 },
    { id: 169, nombre: 'Tena', provinciaId: 15 },
    { id: 170, nombre: 'Archidona', provinciaId: 15 },
    { id: 171, nombre: 'El Chaco', provinciaId: 15 },
    { id: 172, nombre: 'Quijos', provinciaId: 15 },
    { id: 173, nombre: 'Carlos Julio Arosemena Tola', provinciaId: 15 },
    { id: 174, nombre: 'Pastaza', provinciaId: 16 },
    { id: 175, nombre: 'Mera', provinciaId: 16 },
    { id: 176, nombre: 'Santa Clara', provinciaId: 16 },
    { id: 177, nombre: 'Arajuno', provinciaId: 16 },
    { id: 178, nombre: 'Quito', provinciaId: 17 },
    { id: 179, nombre: 'Cayambe', provinciaId: 17 },
    { id: 180, nombre: 'Mejia', provinciaId: 17 },
    { id: 181, nombre: 'Pedro Moncayo', provinciaId: 17 },
    { id: 182, nombre: 'Rumiñahui', provinciaId: 17 },
    { id: 183, nombre: 'San Miguel de Los Bancos', provinciaId: 17 },
    { id: 184, nombre: 'Pedro Vicente Maldonado', provinciaId: 17 },
    { id: 185, nombre: 'Puerto Quito', provinciaId: 17 },
    { id: 186, nombre: 'Ambato', provinciaId: 18 },
    { id: 187, nombre: 'Baños de Agua Santa', provinciaId: 18 },
    { id: 188, nombre: 'Cevallos', provinciaId: 18 },
    { id: 189, nombre: 'Mocha', provinciaId: 18 },
    { id: 190, nombre: 'Patate', provinciaId: 18 },
    { id: 191, nombre: 'Quero', provinciaId: 18 },
    { id: 192, nombre: 'San Pedro de Pelileo', provinciaId: 18 },
    { id: 193, nombre: 'Santiago de Píllaro', provinciaId: 18 },
    { id: 194, nombre: 'Tisaleo', provinciaId: 18 },
    { id: 195, nombre: 'Zamora', provinciaId: 19 },
    { id: 196, nombre: 'Chinchipe', provinciaId: 19 },
    { id: 197, nombre: 'Nangaritza', provinciaId: 19 },
    { id: 198, nombre: 'Yacuambi', provinciaId: 19 },
    { id: 199, nombre: 'Yantzaza (Yanzatza)', provinciaId: 19 },
    { id: 200, nombre: 'El Pangui', provinciaId: 19 },
    { id: 201, nombre: 'Centinela del Cóndor', provinciaId: 19 },
    { id: 202, nombre: 'Palanda', provinciaId: 19 },
    { id: 203, nombre: 'Paquisha', provinciaId: 19 },
    { id: 204, nombre: 'San Cristóbal', provinciaId: 20 },
    { id: 205, nombre: 'Isabela', provinciaId: 20 },
    { id: 206, nombre: 'Santa Cruz', provinciaId: 20 },
    { id: 207, nombre: 'Lago Agrio', provinciaId: 21 },
    { id: 208, nombre: 'Gonzalo Pizarro', provinciaId: 21 },
    { id: 209, nombre: 'Putumayo', provinciaId: 21 },
    { id: 210, nombre: 'Shushufindi', provinciaId: 21 },
    { id: 211, nombre: 'Sucumbíos', provinciaId: 21 },
    { id: 212, nombre: 'Cascales', provinciaId: 21 },
    { id: 213, nombre: 'Cuyabeno', provinciaId: 21 },
    { id: 214, nombre: 'Orellana', provinciaId: 22 },
    { id: 215, nombre: 'Aguarico', provinciaId: 22 },
    { id: 216, nombre: 'La Joya de Los Sachas', provinciaId: 22 },
    { id: 217, nombre: 'Loreto', provinciaId: 22 },
    { id: 218, nombre: 'Santo Domingo', provinciaId: 23 },
    { id: 219, nombre: 'Santa Elena', provinciaId: 24 },
    { id: 220, nombre: 'La Libertad', provinciaId: 24 },
    { id: 221, nombre: 'Salinas', provinciaId: 24 },
    { id: 222, nombre: 'Las Golondrinas', provinciaId: 25 },
    { id: 223, nombre: 'Manga del Cura', provinciaId: 25 },
    { id: 224, nombre: 'El Piedrero', provinciaId: 25 },
  ];

  private parroquias: Parroquia[] = [
    { id: 272, nombre: 'Lizarzaburu', cantonId: 43 },
    { id: 273, nombre: 'Maldonado', cantonId: 43 },
    { id: 274, nombre: 'Velasco', cantonId: 43 },
    { id: 275, nombre: 'Veloz', cantonId: 43 },
    { id: 276, nombre: 'Yaruquíes', cantonId: 43 },
    { id: 277, nombre: 'Riobamba', cantonId: 43 },
    { id: 278, nombre: 'Cacha (Cab. En Machángara)', cantonId: 43 },
    { id: 279, nombre: 'Calpi', cantonId: 43 },
    { id: 280, nombre: 'Cubijíes', cantonId: 43 },
    { id: 281, nombre: 'Flores', cantonId: 43 },
    { id: 282, nombre: 'Licán', cantonId: 43 },
    { id: 283, nombre: 'Licto', cantonId: 43 },
    { id: 284, nombre: 'Pungalá', cantonId: 43 },
    { id: 285, nombre: 'Punín', cantonId: 43 },
    { id: 286, nombre: 'Quimiag', cantonId: 43 },
    { id: 287, nombre: 'San Juan', cantonId: 43 },
    { id: 288, nombre: 'San Luis', cantonId: 43 },
    { id: 289, nombre: 'Alausí', cantonId: 44 },
    { id: 290, nombre: 'Achupallas', cantonId: 44 },
    { id: 291, nombre: 'Cumandá', cantonId: 44 },
    { id: 292, nombre: 'Guasuntos', cantonId: 44 },
    { id: 293, nombre: 'Huigra', cantonId: 44 },
    { id: 294, nombre: 'Multitud', cantonId: 44 },
    { id: 295, nombre: 'Pistishí (Nariz del Diablo)', cantonId: 44 },
    { id: 296, nombre: 'Pumallacta', cantonId: 44 },
    { id: 297, nombre: 'Sevilla', cantonId: 44 },
    { id: 298, nombre: 'Sibambe', cantonId: 44 },
    { id: 299, nombre: 'Tixán', cantonId: 44 },
    { id: 300, nombre: 'Cajabamba', cantonId: 45 },
    { id: 301, nombre: 'Sicalpa', cantonId: 45 },
    { id: 302, nombre: 'Villa La Unión (Cajabamba)', cantonId: 45 },
    { id: 303, nombre: 'Cañi', cantonId: 45 },
    { id: 304, nombre: 'Columbe', cantonId: 45 },
    { id: 305, nombre: 'Juan de Velasco (Pangor)', cantonId: 45 },
    {
      id: 306,
      nombre: 'Santiago de Quito (Cab. En San Antonio de Quito)',
      cantonId: 45,
    },
    { id: 307, nombre: 'Chambo', cantonId: 46 },
    { id: 308, nombre: 'Chunchi', cantonId: 47 },
    { id: 309, nombre: 'Capzol', cantonId: 47 },
    { id: 310, nombre: 'Compud', cantonId: 47 },
    { id: 311, nombre: 'Gonzol', cantonId: 47 },
    { id: 312, nombre: 'Llagos', cantonId: 47 },
    { id: 313, nombre: 'Guamote', cantonId: 48 },
    { id: 314, nombre: 'Cebadas', cantonId: 48 },
    { id: 315, nombre: 'Palmira', cantonId: 48 },
    { id: 316, nombre: 'El Rosario', cantonId: 49 },
    { id: 317, nombre: 'La Matriz', cantonId: 49 },
    { id: 318, nombre: 'Guano', cantonId: 49 },
    { id: 319, nombre: 'Guanando', cantonId: 49 },
    { id: 320, nombre: 'Ilapo', cantonId: 49 },
    { id: 321, nombre: 'La Providencia', cantonId: 49 },
    { id: 322, nombre: 'San Andrés', cantonId: 49 },
    { id: 323, nombre: 'San Gerardo de Pacaicaguán', cantonId: 49 },
    { id: 324, nombre: 'San Isidro de Patulú', cantonId: 49 },
    { id: 325, nombre: 'San José del Chazo', cantonId: 49 },
    { id: 326, nombre: 'Santa Fé de Galán', cantonId: 49 },
    { id: 327, nombre: 'Valparaíso', cantonId: 49 },
    { id: 328, nombre: 'Pallatanga', cantonId: 50 },
    { id: 329, nombre: 'Penipe', cantonId: 51 },
    { id: 330, nombre: 'El Altar', cantonId: 51 },
    { id: 331, nombre: 'Matus', cantonId: 51 },
    { id: 332, nombre: 'Puela', cantonId: 51 },
    { id: 333, nombre: 'San Antonio de Bayushig', cantonId: 51 },
    { id: 334, nombre: 'La Candelaria', cantonId: 51 },
    { id: 335, nombre: 'Bilbao (Cab. En Quilluyacu)', cantonId: 51 },
    { id: 336, nombre: 'Cumandá', cantonId: 52 },
  ];

  private barrios: Barrio[] = [
    { id: 1, nombre: 'Ainche', parroquiaId: 307 },
    { id: 2, nombre: 'Batan', parroquiaId: 307 },
    { id: 3, nombre: 'Central', parroquiaId: 307 },
    { id: 4, nombre: 'Catequilla', parroquiaId: 307 },
    { id: 5, nombre: 'Chisimilan', parroquiaId: 307 },
    { id: 6, nombre: 'Chugllin', parroquiaId: 307 },
    { id: 7, nombre: 'Cuba', parroquiaId: 307 },
    { id: 8, nombre: 'Dolorosa', parroquiaId: 307 },
    { id: 9, nombre: 'El Carmen', parroquiaId: 307 },
    { id: 10, nombre: 'Gualanac', parroquiaId: 307 },
    { id: 11, nombre: 'Guarugtus', parroquiaId: 307 },
    { id: 12, nombre: 'Guilbut', parroquiaId: 307 },
    { id: 13, nombre: 'Jesus del Gran Poder', parroquiaId: 307 },
    { id: 14, nombre: 'Julquis', parroquiaId: 307 },
    { id: 15, nombre: 'Llio', parroquiaId: 307 },
    { id: 16, nombre: 'Magdalena', parroquiaId: 307 },
    { id: 17, nombre: 'Pantaño', parroquiaId: 307 },
    { id: 18, nombre: 'Pantus', parroquiaId: 307 },
    { id: 19, nombre: 'Paraiso', parroquiaId: 307 },
    { id: 20, nombre: 'Quintus', parroquiaId: 307 },
    { id: 21, nombre: 'Recreo', parroquiaId: 307 },
    { id: 22, nombre: 'Rosario', parroquiaId: 307 },
    { id: 23, nombre: 'Rumicruz', parroquiaId: 307 },
    { id: 24, nombre: 'San Jorge', parroquiaId: 307 },
    { id: 25, nombre: 'San Juan', parroquiaId: 307 },
    { id: 26, nombre: 'San Miguel de Guarugtus', parroquiaId: 307 },
    { id: 27, nombre: 'San Pedro del Quinto', parroquiaId: 307 },
    { id: 28, nombre: 'San Sebastian', parroquiaId: 307 },
    { id: 29, nombre: 'Santa Rosa', parroquiaId: 307 },
    { id: 30, nombre: 'Santo Cristo', parroquiaId: 307 },
    { id: 31, nombre: 'Tambo', parroquiaId: 307 },
    { id: 32, nombre: 'Tejar', parroquiaId: 307 },
    { id: 33, nombre: 'Titaycun', parroquiaId: 307 },
    { id: 34, nombre: 'Tunshi San Miguel', parroquiaId: 307 },
    { id: 35, nombre: 'Tunshi San Pedro', parroquiaId: 307 },
    { id: 36, nombre: 'Ulpan', parroquiaId: 307 },
    { id: 37, nombre: 'Vergel', parroquiaId: 307 },
  ];

  getProvincias(): Provincia[] {
    return this.provincias;
  }

  getCantonesByProvinciaId(provinciaId: number): Canton[] {
    return this.cantones.filter((canton) => canton.provinciaId === provinciaId);
  }

  getParroquiasByCantonId(cantonId: number): Parroquia[] {
    return this.parroquias.filter(
      (parroquia) => parroquia.cantonId === cantonId
    );
  }

  getBarriosByParroquiaId(parroquiaId: number) {
    return this.barrios.filter((barrio) => barrio.parroquiaId === parroquiaId);
  }
}
